- name: Restart PostgreSQL
  systemd:
    name: postgresql
    state: restarted
    enabled: true

- name: Restart firewalld
  command: sudo firewall-cmd --reload
  when: ansible_facts['os_family'] == "RedHat"